import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from 'antd';
import { getServerSession } from 'next-auth';

import Sidebar from '@/components/etc/sidebar';
import PageFooter from '@/components/etc/footer';
import SessionProvider from '@/components/etc/session-provider';

export const metadata = {
    title: 'Data.mu',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo.png'
    }
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();
    
    return (
        <html lang='en'>
            <body>
                <SessionProvider session={session}>
                    <AntdRegistry>
                        <Layout style={{ minHeight: '100vh' }}>
                            {session && <Sidebar role={session.user.email} />}
                            <Layout>
                                {children}
                                {session && <PageFooter />}
                            </Layout>
                        </Layout>
                    </AntdRegistry>
                </SessionProvider>
            </body>
        </html>
    );
}